<definitions targetNamespace="http://rtu.ws.es.ormazabal.www/" name="GetStationInfoService" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:tns="http://rtu.ws.es.ormazabal.www/" xmlns:soap12="http://schemas.xmlsoap.org/wsdl/soap12/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns="http://schemas.xmlsoap.org/wsdl/">
   <types>
      <xsd:schema>
         <xsd:import namespace="http://rtu.ws.es.ormazabal.www/" schemaLocation="schemas/getstationinfo-ws-orm.xsd"/>
      </xsd:schema>
   </types>
   <message name="GetStationInfo">
      <part name="parameters" element="tns:GetStationInfo"/>
   </message>
   <message name="GetStationInfoResponse">
      <part name="parameters" element="tns:GetStationInfoResponse"/>
   </message>
   <message name="Fault">
      <part name="fault" element="tns:Fault"/>
   </message>
   <portType name="GetStationInfo">
      <operation name="GetStationInfo">
         <input message="tns:GetStationInfo"/>
         <output message="tns:GetStationInfoResponse"/>
         <fault message="tns:Fault" name="Fault"/>
      </operation>
   </portType>
   <binding name="GetStationInfoPortBinding12" type="tns:GetStationInfo">
      <soap12:binding transport="http://schemas.xmlsoap.org/soap/http" style="document"/>
      <operation name="GetStationInfo">
         <soap12:operation soapAction="" soapActionRequired="false"/>
         <input>
            <soap12:body use="literal"/>
         </input>
         <output>
            <soap12:body use="literal"/>
         </output>
         <fault name="Fault">
            <soap12:fault name="Fault" use="literal"/>
         </fault>
      </operation>
   </binding>
   <service name="GetStationInfoService">
      <port name="GetStationInfoPort12" binding="tns:GetStationInfoPortBinding12">
         <soap12:address location="http://localhost:8084/wsrtu/GetStationInfo"/>
      </port>
   </service>
</definitions>